language: node_js
stages:
  - name: test
  - name: deploy
    if: tag IS present

node_js: 
  - "lts/*"

jobs:
  include:
    - stage: test
      install:
        - npm i -g codecov
        - npm i
      script:
        - npm run lint
        - npm test
      after_success:
        - codecov
    - stage: deploy
      script: ./scripts/release.sh