language: node_js
node_js: 
  - "lts/*"
install:
  - npm i -g codecov
  - npm i
script:
  - npm run lint
  - npm test
  - codecov
jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: ./scripts/release.sh