language: node_js
node_js: 
  - "lts/*"
stages:
  - name: test
  - name: deploy
    if: tag IS present
install:
  - npm i -g codecov
  - npm i
script:
  - npm run lint
  - npm test
  - codecov
jobs:
  include:
    - stage: deploy
      script: ./scripts/release.sh